[build]
builder = "NIXPACKS"

[deploy]
startCommand = "java -jar target/local-inventory-manager-0.0.1-SNAPSHOT.jar"
healthcheckPath = "/api/cors/health"
healthcheckTimeout = 300

[variables]
PORT = "8080"
SPRING_PROFILES_ACTIVE = "production"